jobs:
  deploy:
    working_directory: ~/backend
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            npm install
      - run:
          command: >
            npm start
      - heroku/deploy-via-git
orbs:
  heroku: circleci/heroku@1.2.6
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - deploy
